### ISSUE TITLE
Modrinth Integration + `add` command

### ISSUE THREAD

**Issue by zeke-io** [zeke-io/chain#26]
The `add` command will allow you to add dependencies from the command line.

```bash
chain add plugin1
```

## How?

For this to be possible, Chain would have to look for these dependencies somewhere, the first place that comes to mind is [Modrinth](https://modrinth.com/) with its public API.

It is possible to find and download dependencies with the Modrinth API, but to download the proper versions for these dependencies, we need to provide details about the server.jar like the `version`, and `loader` (fabric, paper, etc.).
To provide these details, we could replace the `server-jar` property for a more detailed `server` property.

### chain.yml

```yml
# The "server-jar" property will be removed and replaced by this "server" property
server:
  source: <url or path>
  version: 1.20.2
  brand: paper
```

By providing the version and brand of the server, we can download the proper versions for dependencies. This will also make it possible to download the server.jar without providing the source (path or url), this will be a separate feature.

```yml
dependencies:
  spark:
    source: https://ci.lucko.me/job/spark/384/artifact/spark-bukkit/build/libs/spark-1.10.43-bukkit.jar
  # the key will be used as the id, and its value is the version id from modrinth
  simple-voice-chat: 
    version: 7zIB5LVU
```

When adding a dependency with the `add` command, using the server's brand and version properties, Chain will look for the appropiate version id from modrinth, download the dependency and add it to dependencies.
