### ISSUE TITLE
Downloading server jars without `source`

### ISSUE THREAD

**Issue by zeke-io** [zeke-io/chain#28]
Currently you need to provide the `source` property along the `brand` and `version` properties in the `chain.yml` file:

```yaml
# chain.yml
server:
  source: https://api.papermc.io/v2/projects/paper/versions/1.20.2/builds/222/downloads/paper-1.20.2-222.jar
  brand: paper
  version: 1.20.2
```

But I am thinking of making `source` optional, and use the `brand` and `version` properties to download the appropiate server.jar file, removing the need to find the URL to get the server runtime.

**However, I am not aware of any platforms/APIs that provide a URL to download servers with specific version and type (paper, spigot, waterfall, forge, etc.).**
